### ISSUE TITLE
mixinが動作しない

### ISSUE THREAD

**Issue by hata-tomoyuki** [ROKO3B/exercises1#4]
スマホサイズでmixinが動作しない

**Comment by hata-tomoyuki** [comment]
メディアクエリは正常に動作しているようです。

flex-directionが動作していないのは
display: flexと併用していないためですね。

https://www.loom.com/share/dfe7688de09e46db887fc9a9cb597c27

**Comment by ROKO3B** [comment]
解決しました。ありがとうございました。
この摸写は終了して次の摸写に取り掛かろうと思います！
